services:
  blog:
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-}
        NEXT_PUBLIC_GOOGLE_MEASUREMENT_ID: ${NEXT_PUBLIC_GOOGLE_MEASUREMENT_ID:-}
        NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: ${NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION:-}
        NEXT_PUBLIC_NAVER_SITE_VERIFICATION: ${NEXT_PUBLIC_NAVER_SITE_VERIFICATION:-}
        NEXT_PUBLIC_UTTERANCES_REPO: ${NEXT_PUBLIC_UTTERANCES_REPO:-}
        NEXT_PUBLIC_GOOGLE_ADSENSE_DISABLE: ${NEXT_PUBLIC_GOOGLE_ADSENSE_DISABLE:-}
        NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT: ${NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT:-}
        REVALIDATE_HOURS: ${REVALIDATE_HOURS:-}
